### PR TITLE
Fix src geometry by convertToCell

### LINKED ISSUE #93: Source geometry is confusing
MFE

```julia
using JUDI
using SegyIO
datapath = joinpath(dirname(pathof(JUDI)))*"/../data/"
nsrc = 2
block = segy_read(datapath*"unit_test_shot_records_$(nsrc).segy"; warn_user=false)
src_geometry = Geometry(block; key="source", segy_depth_key="SourceSurfaceElevation")
println(src_geometry.xloc)    
```

This is a part of the test and it outputs `src_geometry.xloc` as

```julia

julia> println(src_geometry.xloc) 
Float32[100.0, 1100.0]

```

I personally find it quite confusing because there are 2 sources but only here is 1 vector for `xloc`. Typically this means they are simultaneous but in this case they are not.

### PR DESCRIPTION
**Pull request by ziyiyin97**
fix #93 

This would really be the minimal change, i.e. if. key is source, then do `convertToCell`. A couple of test cases need to be adjusted according to the change.
Another change I made it to make `Geometry` struct typed. This has nothing to do with the problem itself, but why not : )

### CODE REVIEW

**Review by mloubout — APPROVED** [review]

**Comment by ziyiyin97** [comment]
The project.toml got v2.6.5 from the last PR #91  but you didn't release v2.6.5 yet in the github Releases. So I think we still leave v2.6.5 in project.toml and release it? It is an addition to PR #91 anyway @mloubout

**Comment by mloubout** [comment]
Yes will make a new release at some point with the various minor PRs

File: src/TimeModeling/Types/GeometryStructure.jl [hunk 1]
```diff
@@ -21,7 +21,7 @@ mutable struct GeometryIC{T} <: Geometry
 end
 
 # Out-of-core geometry structure, contains look-up table instead of coordinates
-mutable struct GeometryOOC{T} <: Geometry
+mutable struct GeometryOOC{T} <: Geometry{T}
```
Comment (mloubout) [inline src/TimeModeling/Types/GeometryStructure.jl:24]: FYI this is not how you use parametric types. T isn't used anywhere you are just creating a weird type with undefined eltype.

Comment (ziyiyin97) [reply src/TimeModeling/Types/GeometryStructure.jl:24]: This might be beneficial for future developments, i.e. developers can do

```julia

function f(g::Geometry{T})

```

no?

Comment (mloubout) [reply src/TimeModeling/Types/GeometryStructure.jl:24]: It has zero use unless it actually implement a parametric type. It's is actually more dangerous/bad that good since you allow awful stuff like

```
struct test{T}
 var::Float32
end

a = test{Float64}(1f0)
```

Parametric type are not for decoration it needs to be done properly

Comment (ziyiyin97) [reply src/TimeModeling/Types/GeometryStructure.jl:24]: But in this case

```julia

abstract type Geometry{T} end

# In-core geometry structure for seismic header information
mutable struct GeometryIC{T} <: Geometry{T}
    xloc::CoordT  # Array of receiver positions (fixed for all experiments)
    yloc::CoordT
    zloc::CoordT
    dt::Array{T,1}
    nt::Array{Integer,1}
    t::Array{T,1}
end

# Out-of-core geometry structure, contains look-up table instead of coordinates
mutable struct GeometryOOC{T} <: Geometry{T}
    container::Array{SegyIO.SeisCon,1}
    dt::Array{T,1}
    nt::Array{Integer,1}
    t::Array{T,1}
    nsamples::Array{Integer,1}
    key::String
    segy_depth_key::String
end

```

both of its subtypes (GeometryIC and GeometryOOC) are typed by T. Then this

```julia
function f(g::Geometry{T})
```
actually makes sense because it forces `g` to either come from `GeometryIC{T}` or `GeometryOOC{T}`, right? If `g` is `GeometryIC{T1}` and `T1 != T` then it doesn't fall into this function `f`
