### PR TITLE
fix reduce

### LINKED ISSUE #76: Forward modeling error
MFE is

```julia
using JUDI
using LinearAlgebra

n = (50, 50)
d = (10f0, 10f0)
o = (0f0, 0f0)
v = 1.5f0 * ones(Float32, n)
m = 1f0./v.^2f0

model = Model(n,d,o,m; nb=80)

nsrc = 3
nrec = 50

dtS = dtR = 4f0
timeS = timeR = 1000f0

xsrc = convertToCell([100f0, 200f0, 300f0])
ysrc = convertToCell(range(0f0,stop=0f0,length=nsrc))
zsrc = convertToCell(range(10f0,stop=10f0,length=nrec))

srcGeometry = Geometry(xsrc, ysrc, zsrc; dt=dtS, t=timeS)
wavelet = ricker_wavelet(timeS,dtS,0.015f0)

q = judiVector(srcGeometry, wavelet)

xrec = range(d[1],stop=(n[1]-1)*d[1],length=nrec)
yrec = 0f0
zrec = range(10f0, stop=10f0, length=nrec)

recGeometry = Geometry(xrec,yrec,zrec; dt=dtR, t=timeR, nsrc=nsrc)

ntComp = get_computational_nt(srcGeometry, recGeometry, model)
info = Info(prod(n), nsrc, ntComp)

opt = Options()

F = judiProjection(info, recGeometry)*judiModeling(info, model; options=opt)*adjoint(judiProjection(info, srcGeometry))

dobs = F*q

println(norm(dobs.data[2]-dobs.data[3])) # this is 0
```

It works fine with 2 sources but when it goes to 3 sources, the 2nd and 3rd shot records are exactly the same. I'll look into how the new parallel strategy affected this (possibly the error comes from #71 )

### PR DESCRIPTION
**Pull request by ziyiyin97**
Fixes #76 

@ziyiyin97 I told you multiple times how to tag an issue in a PR!

### CODE REVIEW

File: src/TimeModeling/Modeling/distributed.jl [hunk 1]
```diff
@@ -201,10 +201,10 @@ end
 Reduce one level of the reduction tree consisting of `nleaf` futures. Each `leaf`
 reduces into itself `futures[i]`.
 """
-function reduce_level!(futures::Vector{_TFuture}, nleaf::Int)
+function reduce_level!(futures::Vector{_TFuture}, nleaf::Int, m::Int, pids::Array{Int})
     nleaf == 0 && return
     @sync for i = 1:nleaf
-        @async remotecall_fetch(local_reduce!, futures[i].where, futures[i], futures[nleaf+i])
```
Comment (ziyiyin97) [inline src/TimeModeling/Modeling/distributed.jl:207]: main problem is here should be `m` not `nleaf`

Comment (mloubout) [reply src/TimeModeling/Modeling/distributed.jl:207]: From the names/syntax I hardly think you trked to fix it and understand it but only copy pasted and made up a sentence for it

Comment (ziyiyin97) [reply src/TimeModeling/Modeling/distributed.jl:207]: I followed DistributedOperations.jl

Comment (mloubout) [reply src/TimeModeling/Modeling/distributed.jl:207]: You just took it and brute force copy paste it. without checking what I changed and how it can realte. Here is proper fix:

https://github.com/slimgroup/JUDI.jl/compare/forfrancis?expand=1

File: src/TimeModeling/Modeling/distributed.jl [hunk 2]
```diff
@@ -231,13 +231,15 @@ function reduce!(futures::Vector{_TFuture})
...
+    
     # Reduce the reminder
-    reduce_level!(futures, R)
+    reduce_level!(futures, R, m, pids)
 
     # Binary tree reduction
     for l = L:-1:1
         m = 2^(l-1)
-        reduce_level!(futures, m)
+        reduce_level!(futures, m, m, pids)
```
Comment (ziyiyin97) [inline src/TimeModeling/Modeling/distributed.jl:242]: Thanks for your branch `forfrancis` you also need to do
`reduce_level!(futures, m, m)`
at this line @mloubout

**Comment by mloubout** [comment]
Small (don't need Judi) test would be nice but looks fine. Change version to 2.6.1

**Comment by ziyiyin97** [comment]
Emm still ain't correct. I've taken another look with a 5 source example -- it seems to mess up the order of `2, 4, 5`-th shot

**Comment by ziyiyin97** [comment]
What kind of test do you @mloubout want to add BTW? If we want to make sure it's 100% working well, we have to add one more dummy function to `_parallel_functions`. Do you have any better suggestion?

**Comment by mloubout** [comment]
No you don't just loop spawn then reduce where you know the result

**Comment by ziyiyin97** [comment]
Oh I seems to understand this behavior: the reduce step for time modeling is basically a stack of judiVectors. During each step of the reduce, we have to stack the neighbors because the order really matters. So this line is https://github.com/slimgroup/JUDI.jl/blob/b6384c5636578d2df72b9b684dc2df110ff922b2/src/TimeModeling/Modeling/distributed.jl#L238 problematic.

Basically if we have 4 sources, we have to first stack 1,2 and 3,4 in the first round, then stack 1,3 in the 2nd round. Now it's stacking 1,3 and 2,4 in the first round, so its ordering messed up.

**Comment by mloubout** [comment]
Yes basically should only need to change the loops indices to fix it. I.e reduce last m then loop every two and reduce next

**Comment by ziyiyin97** [comment]
Then do you have any suggestion on how to reduce the remainder, i.e. reduce 5,6,7 when there are 7 futures

**Comment by ziyiyin97** [comment]
My current strategy is (for 7 futures):

first stack 1,2 ; 3,4 ; 5,6 (since there are 3 remainders, we stack 3 times)

then the ones to be reduce next are 1,3,5 (from previous reductions) and 7 (who didn't get into reduction in the previous round)

**Comment by mloubout** [comment]
You just have to change the loop index why are you making things complicated

**Comment by mloubout** [comment]
```
for i=1:2:2*nleaf
remotecall_fetch(local_reduce!, futures[i].where, futures[i], futures[i+1])
```

And that's all it takes.

**Comment by ziyiyin97** [comment]
No in the 2nd level, `i` should talk to `i+2` not `i+1` any more

**Comment by mloubout** [comment]
deleteat! after loop

**Comment by ziyiyin97** [comment]
OK `deleteat` should be the cleanest way! Thanks

**Review by mloubout — APPROVED** [review]

**Comment by ziyiyin97** [comment]
Rebased
